controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    pid_1: { p: 8.0, i: 0, d: 0.001 }
    pid_2: { p: 8.0, i: 0, d: 0.001 }
    pid_3: { p: 8.0, i: 0, d: 0.001 }
    pid_4: { p: 8.0, i: 0, d: 0.001 }
    Wheel_track: 0.400
    Wheel_base: 0.400
    Wheel_R: 0.07625
    Odom_mode: true

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
